FROM ubuntu
MAINTAINER woochul <crepers12@hanmail.net>

RUN apt-get update
RUN apt-get install memcached

RUN service memcached restart

EXPOSE 11211


#docker run -it --name ubuntu1404 ubuntu /bin/bash




